Repository mlpack/ensmallen, pull requests merged in 2019-09, with the labels that each got.

#127 use fast solve
  include/ensmallen_bits/fw/atoms.hpp
  include/ensmallen_bits/fw/update_span.hpp
  include/ensmallen_bits/sdp/primal_dual_impl.hpp
Labels: c: optimizers, s: needs review

#129 Switch mlpack with ensmallen in callback docs
  doc/callbacks.md
Labels: c: documentation, s: needs review, t: bugfix

#131 Minor compatibility fixes for ensmallen 1.x
  include/ensmallen_bits/function/arma_traits.hpp
  include/ensmallen_bits/sdp/lrsdp_function.hpp
  include/ensmallen_bits/sdp/sdp.hpp
Labels: c: optimizers, t: added feature

#133 ensure armadillo version check uses the same numbers as CMakeLists.txt
  include/ensmallen.hpp
Labels: c: optimizers, s: needs review, s: unanswered, t: bugfix

#134 best practice: set bash option to terminate shell upon expected error
  rel/ensmallen-release.sh
Labels: c: build system, t: added feature

#136 Check L-BFGS scaling factor for convergence
  HISTORY.md
  include/ensmallen_bits/lbfgs/lbfgs_impl.hpp
Labels: c: optimizers, t: bugfix

#135 ParallelSGD omp fix
  HISTORY.md
  include/ensmallen_bits/config.hpp
  include/ensmallen_bits/parallel_sgd/parallel_sgd_impl.hpp
  tests/parallel_sgd_test.cpp
Labels: c: tests, s: needs review, t: bugfix
