Repository mlpack/ensmallen, pull requests merged in 2019-03, with the labels that each got.

#92 Add newline to end of `de.hpp` file
  include/ensmallen_bits/de/de.hpp
Labels: c: optimizers, t: bugfix

#94 Add issue templates.
  .github/ISSUE_TEMPLATE/0-bug.md
  .github/ISSUE_TEMPLATE/1-documentation.md
  .github/ISSUE_TEMPLATE/2-question.md
Labels: c: documentation, s: needs review, s: unanswered, t: added feature

#95 `cyclical_decay.hpp` BibTeX fix
  HISTORY.md
  include/ensmallen_bits/sgdr/cyclical_decay.hpp
Labels: s: needs review, s: unanswered, s: unlabeled

#97 Adjust tolerances for SPSA test.
  tests/spsa_test.cpp
Labels: c: optimizers, t: bugfix

#98 documentation fixes
  doc/function_types.md
  doc/optimizers.md
Labels: c: documentation, s: needs review, s: unanswered, t: bugfix
