Repository mlpack/ensmallen, pull requests merged in 2019-05, with the labels that each got.

#100 fix: don't assume that arma::eig_sym() always succeeds
  include/ensmallen_bits/sdp/primal_dual_impl.hpp
  tests/sdp_primal_dual_test.cpp
Labels: c: optimizers, s: needs review, t: bugfix

#111 minor style fix + added TODO
  tests/sdp_primal_dual_test.cpp
Labels: c: optimizers, s: needs review, t: bugfix

#112 workaround for MSVC bug
  include/ensmallen_bits/fw/atoms.hpp
Labels: c: optimizers, s: needs review, t: bugfix

#115 Fix compilation warnings
  HISTORY.md
  doc/optimizers.md
  include/ensmallen_bits/qhadam/qhadam_update.hpp
  include/ensmallen_bits/spsa/spsa.hpp
  include/ensmallen_bits/spsa/spsa_impl.hpp
Labels: c: optimizers

#116 Enable minimal code style checks
  .travis.yml
  CMakeLists.txt
Labels: c: build system, c: tests, s: needs review, s: unanswered, t: added feature
