Repository mlpack/ensmallen, pull requests merged in 2019-08, with the labels that each got.

#86 Introducing LBest PSO for Unconstrained Optimization Problems
  CMakeLists.txt
  HISTORY.md
  doc/optimizers.md
  include/ensmallen.hpp
  include/ensmallen_bits/pso/init_policies/default_init.hpp
  include/ensmallen_bits/pso/pso.hpp
  include/ensmallen_bits/pso/pso_impl.hpp
  include/ensmallen_bits/pso/update_policies/lbest_update.hpp
  tests/CMakeLists.txt
  tests/pso_test.cpp
Labels: c: optimizers, s: needs review, t: added feature

#109 Providing option to calculate exact objective
  HISTORY.md
  doc/optimizers.md
  include/ensmallen_bits/ada_delta/ada_delta.hpp
  include/ensmallen_bits/ada_delta/ada_delta_impl.hpp
  include/ensmallen_bits/ada_grad/ada_grad.hpp
  include/ensmallen_bits/ada_grad/ada_grad_impl.hpp
  include/ensmallen_bits/adam/adam.hpp
  include/ensmallen_bits/adam/adam_impl.hpp
  include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd.hpp
  include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd_impl.hpp
  include/ensmallen_bits/eve/eve.hpp
  include/ensmallen_bits/eve/eve_impl.hpp
  include/ensmallen_bits/ftml/ftml.hpp
  include/ensmallen_bits/ftml/ftml_impl.hpp
  include/ensmallen_bits/katyusha/katyusha.hpp
  include/ensmallen_bits/katyusha/katyusha_impl.hpp
  include/ensmallen_bits/padam/padam.hpp
  include/ensmallen_bits/qhadam/qhadam.hpp
  include/ensmallen_bits/qhadam/qhadam_impl.hpp
  include/ensmallen_bits/rmsprop/rmsprop.hpp
  include/ensmallen_bits/sarah/sarah.hpp
  include/ensmallen_bits/sarah/sarah_impl.hpp
  include/ensmallen_bits/sgd/sgd.hpp
  include/ensmallen_bits/sgd/sgd_impl.hpp
  include/ensmallen_bits/sgdr/sgdr.hpp
  include/ensmallen_bits/sgdr/sgdr_impl.hpp
  include/ensmallen_bits/sgdr/snapshot_sgdr.hpp
  include/ensmallen_bits/sgdr/snapshot_sgdr_impl.hpp
  include/ensmallen_bits/smorms3/smorms3.hpp
  include/ensmallen_bits/smorms3/smorms3_impl.hpp
  include/ensmallen_bits/spalera_sgd/spalera_sgd.hpp
  include/ensmallen_bits/spalera_sgd/spalera_sgd_impl.hpp
  include/ensmallen_bits/svrg/svrg.hpp
  include/ensmallen_bits/svrg/svrg_impl.hpp
  include/ensmallen_bits/swats/swats.hpp
  include/ensmallen_bits/swats/swats_impl.hpp
  include/ensmallen_bits/wn_grad/wn_grad.hpp
  include/ensmallen_bits/wn_grad/wn_grad_impl.hpp
  tests/momentum_sgd_test.cpp
  tests/nesterov_momentum_sgd_test.cpp
  tests/quasi_hyperbolic_momentum_sgd_test.cpp
  tests/sgd_test.cpp
  tests/svrg_test.cpp
Labels: c: optimizers, s: keep open, s: needs review, t: added feature

#124 Fix PSO bound type
  include/ensmallen_bits/pso/pso.hpp
  include/ensmallen_bits/pso/pso_impl.hpp
Labels: c: optimizers, t: bugfix

#125 Add version names and use Markdown links in HISTORY.md
  HISTORY.md
Labels: s: needs review, t: bugfix

#126 Fix incorrect return type for PSO.
  HISTORY.md
  include/ensmallen_bits/pso/pso.hpp
Labels: c: optimizers, t: bugfix
