Repository mlpack/ensmallen, pull requests merged in 2019-12, with the labels that each got.

#143 32-bit safety in big random number
  tests/callbacks_test.cpp
Labels: c: tests, s: needs review, t: bugfix

#147 Remove 'using namespace std' from problems.
  HISTORY.md
  include/ensmallen_bits/problems/ackley_function_impl.hpp
  include/ensmallen_bits/problems/beale_function_impl.hpp
  include/ensmallen_bits/problems/cross_in_tray_function_impl.hpp
  include/ensmallen_bits/problems/goldstein_price_function_impl.hpp
  include/ensmallen_bits/problems/himmelblau_function_impl.hpp
  include/ensmallen_bits/problems/holder_table_function_impl.hpp
  include/ensmallen_bits/problems/levy_function_n13_impl.hpp
  include/ensmallen_bits/problems/schaffer_function_n2_impl.hpp
  include/ensmallen_bits/problems/schaffer_function_n4_impl.hpp
  include/ensmallen_bits/problems/three_hump_camel_function_impl.hpp
  tests/pso_test.cpp
Labels: c: optimizers, t: bugfix

#145 Update static check terms to match documentation
  HISTORY.md
  include/ensmallen_bits/ada_delta/ada_delta.hpp
  include/ensmallen_bits/ada_grad/ada_grad.hpp
  include/ensmallen_bits/adam/adam.hpp
  include/ensmallen_bits/bigbatch_sgd/adaptive_stepsize.hpp
  include/ensmallen_bits/bigbatch_sgd/backtracking_line_search.hpp
  include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd.hpp
  include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd_impl.hpp
  include/ensmallen_bits/cmaes/cmaes.hpp
  include/ensmallen_bits/cmaes/cmaes_impl.hpp
  include/ensmallen_bits/cmaes/full_selection.hpp
  include/ensmallen_bits/cmaes/random_selection.hpp
  include/ensmallen_bits/cne/cne_impl.hpp
  include/ensmallen_bits/de/de.hpp
  include/ensmallen_bits/de/de_impl.hpp
  include/ensmallen_bits/eve/eve.hpp
  include/ensmallen_bits/eve/eve_impl.hpp
  include/ensmallen_bits/ftml/ftml.hpp
  include/ensmallen_bits/function.hpp
  include/ensmallen_bits/function/add_separable_evaluate.hpp
  include/ensmallen_bits/function/add_separable_evaluate_with_gradient.hpp
  include/ensmallen_bits/function/add_separable_gradient.hpp
  include/ensmallen_bits/function/static_checks.hpp
  include/ensmallen_bits/function/traits.hpp
  include/ensmallen_bits/gradient_descent/gradient_descent.hpp
  include/ensmallen_bits/grid_search/grid_search_impl.hpp
  include/ensmallen_bits/iqn/iqn.hpp
  include/ensmallen_bits/iqn/iqn_impl.hpp
  include/ensmallen_bits/katyusha/katyusha.hpp
  include/ensmallen_bits/katyusha/katyusha_impl.hpp
  include/ensmallen_bits/lbfgs/lbfgs.hpp
  include/ensmallen_bits/padam/padam.hpp
  include/ensmallen_bits/parallel_sgd/parallel_sgd.hpp
  include/ensmallen_bits/problems/generalized_rosenbrock_function.hpp
  include/ensmallen_bits/pso/pso_impl.hpp
  include/ensmallen_bits/qhadam/qhadam.hpp
  include/ensmallen_bits/rmsprop/rmsprop.hpp
  include/ensmallen_bits/sa/sa_impl.hpp
  include/ensmallen_bits/sarah/sarah.hpp
  include/ensmallen_bits/sarah/sarah_impl.hpp
  include/ensmallen_bits/scd/scd.hpp
  include/ensmallen_bits/sgd/sgd.hpp
  include/ensmallen_bits/sgd/sgd_impl.hpp
  include/ensmallen_bits/sgdr/sgdr.hpp
  include/ensmallen_bits/sgdr/sgdr_impl.hpp
  include/ensmallen_bits/sgdr/snapshot_sgdr.hpp
  include/ensmallen_bits/sgdr/snapshot_sgdr_impl.hpp
  include/ensmallen_bits/smorms3/smorms3.hpp
  include/ensmallen_bits/spalera_sgd/spalera_sgd.hpp
  include/ensmallen_bits/spalera_sgd/spalera_sgd_impl.hpp
  include/ensmallen_bits/spsa/spsa_impl.hpp
  include/ensmallen_bits/svrg/svrg.hpp
  include/ensmallen_bits/svrg/svrg_impl.hpp
  include/ensmallen_bits/swats/swats.hpp
  include/ensmallen_bits/wn_grad/wn_grad.hpp
  tests/function_test.cpp
Labels: c: documentation, c: optimizers, s: needs review, t: bugfix

#137 AdaBound + AMSBound
  HISTORY.md
  doc/function_types.md
  doc/optimizers.md
  include/ensmallen.hpp
  include/ensmallen_bits/ada_bound/ada_bound.hpp
  include/ensmallen_bits/ada_bound/ada_bound_impl.hpp
  include/ensmallen_bits/ada_bound/ada_bound_update.hpp
  include/ensmallen_bits/ada_bound/ams_bound_update.hpp
  tests/CMakeLists.txt
  tests/ada_bound_test.cpp
Labels: c: optimizers, s: keep open, s: needs review, t: added feature

#148 Add build/test instructions
  CONTRIBUTING.md
  COPYRIGHT.txt
  README.md
  rel/ensmallen-release.sh
Labels: c: build system, c: documentation, c: tests, s: needs review, t: added feature

#138 Lookahead Optimizer: k steps forward, 1 step back
  HISTORY.md
  doc/function_types.md
  doc/optimizers.md
  include/ensmallen.hpp
  include/ensmallen_bits/adam/optimisticadam_update.hpp
  include/ensmallen_bits/callbacks/progress_bar.hpp
  include/ensmallen_bits/callbacks/traits.hpp
  include/ensmallen_bits/de/de.hpp
  include/ensmallen_bits/eve/eve.hpp
  include/ensmallen_bits/function/traits.hpp
  include/ensmallen_bits/lookahead/lookahead.hpp
  include/ensmallen_bits/lookahead/lookahead_impl.hpp
  include/ensmallen_bits/parallel_sgd/parallel_sgd.hpp
  include/ensmallen_bits/pso/pso.hpp
  tests/CMakeLists.txt
  tests/lookahead_test.cpp
Labels: c: optimizers, s: keep open, s: needs review, t: added feature

#153 Lookahead - Synchronization period type fix
  HISTORY.md
  include/ensmallen_bits/lookahead/lookahead.hpp
Labels: c: optimizers, s: needs review, t: bugfix

#154 Add some missing optimizer types.
  doc/function_types.md
Labels: c: documentation, t: bugfix
