Repository mlpack/ensmallen, pull requests merged in 2020-01, with the labels that each got.

#157 Fix typo
  include/ensmallen_bits/problems/schaffer_function_n2.hpp
Labels: c: documentation, s: needs review, t: bugfix

#156 Fix float types and tolerances in some tests.
  HISTORY.md
  tests/lbfgs_test.cpp
  tests/spsa_test.cpp
Labels: c: tests, t: bugfix

#155 Fix Callback passing for SGD based optimizers.
  HISTORY.md
  include/ensmallen_bits/ada_bound/ada_bound.hpp
  include/ensmallen_bits/ada_delta/ada_delta.hpp
  include/ensmallen_bits/ada_grad/ada_grad.hpp
  include/ensmallen_bits/adam/adam.hpp
  include/ensmallen_bits/ftml/ftml.hpp
  include/ensmallen_bits/padam/padam.hpp
  include/ensmallen_bits/qhadam/qhadam.hpp
  include/ensmallen_bits/rmsprop/rmsprop.hpp
  include/ensmallen_bits/smorms3/smorms3.hpp
  include/ensmallen_bits/swats/swats.hpp
  include/ensmallen_bits/wn_grad/wn_grad.hpp
  tests/callbacks_test.cpp
Labels: c: optimizers, t: added feature, t: bugfix

#159 Fix Lookahead MaxIterations() check
  HISTORY.md
  include/ensmallen_bits/lookahead/lookahead.hpp
  include/ensmallen_bits/lookahead/lookahead_impl.hpp
Labels: c: optimizers, s: needs review, t: bugfix

#161 prevent spurious compiler warnings
  include/ensmallen_bits/callbacks/callbacks.hpp
Labels: c: build system, s: needs review

#162 update history
  HISTORY.md
Labels: c: documentation, s: needs review
