Repository mlpack/ensmallen, pull requests merged in 2020-04, with the labels that each got.

#192 Update release scripts
  scripts/ensmallen-release.sh
  scripts/update-website-after-release.sh
Labels: t: added feature

#194 handle SpSubview_col and SpSubview_row in Armadillo 9.870
  HISTORY.md
  include/ensmallen_bits/function/arma_traits.hpp
  include/ensmallen_bits/utility/arma_traits.hpp
Labels: t: added feature, t: bugfix

#181 Fixing ProgressBar()
  HISTORY.md
  include/ensmallen_bits/callbacks/progress_bar.hpp
  tests/callbacks_test.cpp
Labels: c: optimizers, t: bugfix

#195 Update HISTORY.md
  HISTORY.md
Labels: c: documentation, t: bugfix

#197 minor documentation fixes
  HISTORY.md
  doc/callbacks.md
  doc/optimizers.md
Labels: c: documentation

#196 Release version 2.12.1
  CONTRIBUTING.md
  HISTORY.md
  include/ensmallen_bits/ens_version.hpp
  scripts/ensmallen-release.sh
Labels: t: release
