Repository mlpack/ensmallen, pull requests merged in 2020-02, with the labels that each got.

#164 Remove execution right from headers
  include/ensmallen_bits/callbacks/print_loss.hpp
  include/ensmallen_bits/callbacks/progress_bar.hpp
  include/ensmallen_bits/callbacks/store_best_coordinates.hpp
  include/ensmallen_bits/callbacks/timer_stop.hpp
Labels: s: needs review, t: bugfix

#166 Adding bib tex format in the README
  README.md
Labels: c: documentation, s: needs review, t: added feature

#158 AppVeyor config
  .appveyor.yml
  include/ensmallen_bits/problems/aug_lagrangian_test_functions_impl.hpp
  tests/swats_test.cpp
Labels: c: build system, t: added feature

#167 Fix memory leak
  HISTORY.md
  include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd.hpp
  include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd_impl.hpp
  include/ensmallen_bits/lookahead/lookahead.hpp
  include/ensmallen_bits/lookahead/lookahead_impl.hpp
  include/ensmallen_bits/pso/pso.hpp
  include/ensmallen_bits/pso/pso_impl.hpp
  include/ensmallen_bits/sdp/lrsdp_function.hpp
  include/ensmallen_bits/sdp/lrsdp_function_impl.hpp
  include/ensmallen_bits/sgd/sgd.hpp
  include/ensmallen_bits/sgd/sgd_impl.hpp
  include/ensmallen_bits/spalera_sgd/spalera_sgd.hpp
  include/ensmallen_bits/spalera_sgd/spalera_sgd_impl.hpp
  include/ensmallen_bits/svrg/svrg.hpp
  include/ensmallen_bits/svrg/svrg_impl.hpp
Labels: c: optimizers, t: bugfix

#170 Update HISTORY.
  HISTORY.md
Labels: c: documentation, t: bugfix

#169 proposed note on cmake requirements
  README.md
Labels: c: documentation, t: added feature

#171 Require history entry
  .travis.yml
  HISTORY.md
  scripts/ensmallen-release.sh
  scripts/history-update-check.sh
Labels: c: build system, t: added feature
