Repository mlpack/ensmallen, pull requests merged in 2020-08, with the labels that each got.

#149 Add NSGA2
  HISTORY.md
  doc/function_types.md
  doc/optimizers.md
  include/ensmallen.hpp
  include/ensmallen_bits/nsga2/nsga2.hpp
  include/ensmallen_bits/nsga2/nsga2_impl.hpp
  include/ensmallen_bits/problems/fonseca_fleming_function.hpp
  include/ensmallen_bits/problems/problems.hpp
  include/ensmallen_bits/problems/schaffer_function_n1.hpp
  tests/CMakeLists.txt
  tests/callbacks_test.cpp
  tests/nsga2_test.cpp
Labels: c: optimizers, t: added feature

#214 Release version 2.14.0: "No Direction Home"
  CONTRIBUTING.md
  HISTORY.md
  include/ensmallen_bits/ens_version.hpp
Labels: t: release

#217 Set AugLagrangian tolerance based on ElemType
  HISTORY.md
  include/ensmallen_bits/aug_lagrangian/aug_lagrangian_impl.hpp
Labels: c: optimizers, t: bugfix

#216 Fix release script
  HISTORY.md
  scripts/ensmallen-release.sh
Labels: t: bugfix

#220 Fix quotation bug in release script.
  HISTORY.md
  scripts/ensmallen-release.sh
Labels: c: build system, s: unanswered, t: bugfix

#223 Fix implementation of fonesca fleming problem function f1 and f2 type usage and negative signs.
  HISTORY.md
  include/ensmallen_bits/problems/fonseca_fleming_function.hpp
Labels: c: tests, t: bugfix
