Repository mlpack/ensmallen, pull requests merged in 2020-11, with the labels that each got.

#213 Optimizer Summary Report
  HISTORY.md
  doc/callbacks.md
  include/ensmallen.hpp
  include/ensmallen_bits/callbacks/report.hpp
  include/ensmallen_bits/function/traits.hpp
  tests/callbacks_test.cpp
Labels: s: keep open, t: added feature

#238 Release version 2.15.0: "Why Can't I Manage To Grow Any Plants?"
  CONTRIBUTING.md
  HISTORY.md
  include/ensmallen_bits/ens_version.hpp
Labels: t: release

#239 Fix include order of traits which reports depends upon
  HISTORY.md
  include/ensmallen.hpp
Labels: t: bugfix
