Repository mlpack/ensmallen, pull requests merged in 2020-10, with the labels that each got.

#228 Fix SimpleSGDTestFunction arma::fmat test failures
  HISTORY.md
  tests/ada_delta_test.cpp
  tests/ada_grad_test.cpp
Labels: c: tests, t: bugfix

#230 Fix a bug in the function name
  doc/callbacks.md
  include/ensmallen_bits/callbacks/store_best_coordinates.hpp
Labels: c: optimizers, s: keep open, t: bugfix

#226 Incorporate release date with ensmallen version
  HISTORY.md
  include/ensmallen_bits/ens_version.hpp
  scripts/ensmallen-release.sh
Labels: t: added feature

#236 Make sure there's a space in release script output
  HISTORY.md
  scripts/ensmallen-release.sh
Labels: t: bugfix
