Repository mlpack/ensmallen, pull requests merged in 2020-03, with the labels that each got.

#172 not-so-quick fix sanity check for outside of PRs
  .travis.yml
  HISTORY.md
Labels: c: tests, t: bugfix

#175 Re-fix Ensmallen History Mod Checker
  .travis.yml
  HISTORY.md
  scripts/history-update-check.sh
Labels: c: tests, t: bugfix

#174 Example doc fix + add/use default argument.
  doc/function_types.md
  doc/optimizers.md
  include/ensmallen_bits/sa/sa.hpp
  include/ensmallen_bits/sa/sa_impl.hpp
Labels: c: documentation, c: optimizers, t: added feature, t: bugfix

#177 Change 'mathematical optimization' to 'numerical optimization'
  HISTORY.md
  README.md
Labels: c: documentation

#183 Correction in the computation of sigma for the next population in CMA-ES.
  HISTORY.md
  include/ensmallen_bits/cmaes/cmaes_impl.hpp
Labels: c: optimizers, t: bugfix

#186 Use new ensmallen logo
  README.md
Labels: c: documentation

#185 remove sdp deprecated methods
  COPYRIGHT.txt
  HISTORY.md
  doc/function_types.md
  include/ensmallen_bits/sdp/primal_dual.hpp
  include/ensmallen_bits/sdp/primal_dual_impl.hpp
  tests/sdp_primal_dual_test.cpp
Labels: c: optimizers, c: tests
