Repository mlpack/ensmallen, pull requests merged in 2021-07, with the labels that each got.

#305 various fixes for matrix initialisation
  HISTORY.md
  include/ensmallen_bits/problems/schwefel_function.hpp
  include/ensmallen_bits/sa/sa_impl.hpp
  include/ensmallen_bits/sdp/primal_dual_impl.hpp
Labels: c: optimizers, s: unanswered, t: bugfix

#306 Reduce LOC of NSGA-II
  include/ensmallen_bits/nsga2/nsga2.hpp
  include/ensmallen_bits/nsga2/nsga2_impl.hpp
Labels: c: optimizers

#299 Repair MOEAD
  include/ensmallen_bits/moead/decomposition_policies/pbi_decomposition.hpp
  include/ensmallen_bits/moead/moead_impl.hpp
Labels: c: optimizers, t: bugfix

#310 Release version 2.17.0: "Pachis Din Me Pesa Double"
  CONTRIBUTING.md
  HISTORY.md
  include/ensmallen_bits/ens_version.hpp
Labels: s: unanswered, s: unlabeled
