Repository mlpack/ensmallen, pull requests merged in 2021-02, with the labels that each got.

#248 add short example program; expand README with example installation
  HISTORY.md
  README.md
  example.cpp
Labels: c: documentation

#252 Fix Report callback when no steps were taken.
  include/ensmallen_bits/callbacks/report.hpp
Labels: c: optimizers, t: bugfix

#255 Fix compilation issue when ENS_USE_OPENMP is specified.
  HISTORY.md
  tests/parallel_sgd_test.cpp
Labels: c: tests, t: bugfix

#258 Use normal distribution for CNE initial population generation
  HISTORY.md
  include/ensmallen_bits/cne/cne_impl.hpp
  tests/main.cpp
Labels: c: optimizers, t: bugfix

#257 Spelling and grammatical errors
  CONTRIBUTING.md
Labels: c: documentation
