Repository mlpack/ensmallen, pull requests merged in 2021-03, with the labels that each got.

#259 Remove unused `const` to fix compilation warnings
  HISTORY.md
  include/ensmallen_bits/problems/ackley_function.hpp
  include/ensmallen_bits/problems/beale_function.hpp
  include/ensmallen_bits/problems/booth_function.hpp
  include/ensmallen_bits/problems/bukin_function.hpp
  include/ensmallen_bits/problems/colville_function.hpp
  include/ensmallen_bits/problems/drop_wave_function.hpp
  include/ensmallen_bits/problems/easom_function.hpp
  include/ensmallen_bits/problems/eggholder_function.hpp
  include/ensmallen_bits/problems/generalized_rosenbrock_function.hpp
  include/ensmallen_bits/problems/goldstein_price_function.hpp
  include/ensmallen_bits/problems/gradient_descent_test_function.hpp
  include/ensmallen_bits/problems/levy_function_n13.hpp
  include/ensmallen_bits/problems/matyas_function.hpp
  include/ensmallen_bits/problems/mc_cormick_function.hpp
  include/ensmallen_bits/problems/rastrigin_function.hpp
  include/ensmallen_bits/problems/rosenbrock_function.hpp
  include/ensmallen_bits/problems/rosenbrock_wood_function.hpp
  include/ensmallen_bits/problems/schaffer_function_n2.hpp
  include/ensmallen_bits/problems/schwefel_function.hpp
  include/ensmallen_bits/problems/sgd_test_function.hpp
  include/ensmallen_bits/problems/sparse_test_function.hpp
  include/ensmallen_bits/problems/sphere_function.hpp
  include/ensmallen_bits/problems/styblinski_tang_function.hpp
  include/ensmallen_bits/problems/three_hump_camel_function.hpp
  include/ensmallen_bits/problems/wood_function.hpp
Labels: c: optimizers, t: bugfix

#262 Nits on NSGA2
  include/ensmallen_bits/nsga2/nsga2_impl.hpp
Labels: c: documentation

#268 Catch2 update 2.13.4
  HISTORY.md
  tests/LICENSE_1_0.txt
  tests/catch.hpp
Labels: c: tests, t: bugfix

#267 CNE distribution test
  HISTORY.md
  tests/cne_test.cpp
Labels: c: tests

#271 Swapped default params in AugLagrangian docs
  HISTORY.md
  doc/optimizers.md
Labels: c: documentation, t: bugfix

#274 SchafferN1 Initial Point fix
  include/ensmallen_bits/problems/schaffer_function_n1.hpp
Labels: c: tests, t: bugfix

#275 InitPoint
  include/ensmallen_bits/problems/fonseca_fleming_function.hpp
Labels: c: tests, t: bugfix

#276 Clarifying comments about test problems
  HISTORY.md
  include/ensmallen_bits/problems/ackley_function.hpp
  include/ensmallen_bits/problems/beale_function.hpp
  include/ensmallen_bits/problems/booth_function.hpp
  include/ensmallen_bits/problems/bukin_function.hpp
  include/ensmallen_bits/problems/colville_function.hpp
  include/ensmallen_bits/problems/cross_in_tray_function.hpp
  include/ensmallen_bits/problems/drop_wave_function.hpp
  include/ensmallen_bits/problems/easom_function.hpp
  include/ensmallen_bits/problems/eggholder_function.hpp
  include/ensmallen_bits/problems/generalized_rosenbrock_function.hpp
  include/ensmallen_bits/problems/goldstein_price_function.hpp
  include/ensmallen_bits/problems/gradient_descent_test_function.hpp
  include/ensmallen_bits/problems/levy_function_n13.hpp
  include/ensmallen_bits/problems/matyas_function.hpp
  include/ensmallen_bits/problems/mc_cormick_function.hpp
  include/ensmallen_bits/problems/rastrigin_function.hpp
  include/ensmallen_bits/problems/rosenbrock_function.hpp
  include/ensmallen_bits/problems/rosenbrock_wood_function.hpp
  include/ensmallen_bits/problems/schaffer_function_n2.hpp
  include/ensmallen_bits/problems/schwefel_function.hpp
  include/ensmallen_bits/problems/sgd_test_function.hpp
  include/ensmallen_bits/problems/sparse_test_function.hpp
  include/ensmallen_bits/problems/sphere_function.hpp
  include/ensmallen_bits/problems/styblinski_tang_function.hpp
  include/ensmallen_bits/problems/three_hump_camel_function.hpp
  include/ensmallen_bits/problems/wood_function.hpp
Labels: c: documentation, c: tests, t: bugfix

#265 Remove AdamSchafferFunctionN2Test test case
  HISTORY.md
  tests/adam_test.cpp
Labels: c: optimizers

#281 Fix CMAES population size parameter comment
  include/ensmallen_bits/cmaes/cmaes.hpp
Labels: c: documentation
