Repository mlpack/ensmallen, pull requests merged in 2021-06, with the labels that each got.

#291 Doc fix
  doc/function_types.md
Labels: c: documentation, t: bugfix

#289 Make Callback flexible for MultiObjective Optimizers.
  HISTORY.md
  doc/callbacks.md
  include/ensmallen.hpp
  include/ensmallen_bits/callbacks/callbacks.hpp
  include/ensmallen_bits/callbacks/query_front.hpp
  include/ensmallen_bits/callbacks/traits.hpp
  include/ensmallen_bits/nsga2/nsga2_impl.hpp
  tests/callbacks_test.cpp
Labels: t: added feature

#273 Adding ZDT Test Suite
  HISTORY.md
  include/ensmallen_bits/problems/problems.hpp
  include/ensmallen_bits/problems/zdt/zdt1_function.hpp
  include/ensmallen_bits/problems/zdt/zdt2_function.hpp
  include/ensmallen_bits/problems/zdt/zdt3_function.hpp
  include/ensmallen_bits/problems/zdt/zdt4_function.hpp
  include/ensmallen_bits/problems/zdt/zdt6_function.hpp
  tests/nsga2_test.cpp
Labels: c: tests, t: added feature

#269 Implement MOEA/D - DE
  HISTORY.md
  doc/function_types.md
  doc/optimizers.md
  include/ensmallen.hpp
  include/ensmallen_bits/moead/moead.hpp
  include/ensmallen_bits/moead/moead_impl.hpp
  tests/CMakeLists.txt
  tests/callbacks_test.cpp
  tests/moead_test.cpp
Labels: c: optimizers, s: keep open

#293 Introduce Policy Methods for MOEA/D-DE
  HISTORY.md
  doc/optimizers.md
  include/ensmallen_bits/moead/decomposition_policies/pbi_decomposition.hpp
  include/ensmallen_bits/moead/decomposition_policies/tchebycheff_decomposition.hpp
  include/ensmallen_bits/moead/decomposition_policies/weighted_decomposition.hpp
  include/ensmallen_bits/moead/moead.hpp
  include/ensmallen_bits/moead/moead_impl.hpp
  include/ensmallen_bits/moead/weight_init_policies/bbs_init.hpp
  tests/callbacks_test.cpp
  tests/moead_test.cpp
Labels: t: added feature

#295 Add Das-Dennis weight initialization method
  HISTORY.md
  doc/optimizers.md
  include/ensmallen_bits/moead/moead.hpp
  include/ensmallen_bits/moead/weight_init_policies/uniform_init.hpp
  tests/moead_test.cpp
Labels: c: optimizers, t: added feature

#302 Modify HISTORY.md release history
  HISTORY.md
Labels: s: unanswered, s: unlabeled

#300 improved installation and compilation instructions
  HISTORY.md
  README.md
Labels: c: documentation

#303 don't build tests by default
  HISTORY.md
  README.md
  tests/CMakeLists.txt
Labels: c: build system, c: documentation, c: tests

#304 Add Front() back into the NSGA2 class.
  HISTORY.md
  include/ensmallen_bits/nsga2/nsga2.hpp
  include/ensmallen_bits/nsga2/nsga2_impl.hpp
  tests/nsga2_test.cpp
Labels: c: optimizers
