Repository mlpack/ensmallen, pull requests merged in 2021-08, with the labels that each got.

#313 The BUILD_TESTS option was replaced with 'make ensmallen_tests'.
  CMakeLists.txt
  HISTORY.md
Labels: c: tests, s: needs review

#314 Update travis config to build the ensmallen tests
  .travis.yml
Labels: c: tests

#316 update citation to JMLR paper
  README.md
Labels: c: documentation

#315 GradClipByValue callback
  HISTORY.md
  doc/callbacks.md
  include/ensmallen.hpp
  include/ensmallen_bits/callbacks/grad_clip_by_norm.hpp
  include/ensmallen_bits/callbacks/grad_clip_by_value.hpp
  include/ensmallen_bits/callbacks/traits.hpp
  tests/callbacks_test.cpp
Labels: t: added feature
