Repository mlpack/ensmallen, pull requests merged in 2022-04, with the labels that each got.

#211 DemonSGD & DemonAdam
  HISTORY.md
  doc/optimizers.md
  include/ensmallen.hpp
  include/ensmallen_bits/demon_adam/demon_adam.hpp
  include/ensmallen_bits/demon_adam/demon_adam_update.hpp
  include/ensmallen_bits/demon_sgd/demon_sgd.hpp
  include/ensmallen_bits/demon_sgd/demon_sgd_update.hpp
  tests/CMakeLists.txt
  tests/demon_adam_test.cpp
  tests/demon_sgd_test.cpp
Labels: c: optimizers, s: keep open, s: needs review

#342 bump check for min supported version of armadillo
  HISTORY.md
  include/ensmallen.hpp
Labels: t: bugfix

#343 Release version 2.19.0: "Eight Ball Deluxe"
  CONTRIBUTING.md
  HISTORY.md
  include/ensmallen_bits/ens_version.hpp
Labels: t: release
